# -*- coding: utf-8 -*-
"""acefixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HiUSykPhfvaK91MDRxFbzIm7ueVNALQr
"""

files_list = []
import os
def get_files():
    try:
        all_entries = os.listdir(".")
        files = [entry for entry in all_entries if os.path.isfile(os.path.join(".", entry))]
        print("Files in the folder:")
        for file_name in files:
            print(file_name)
            files_list.append(file_name)
    except FileNotFoundError:
        print("Error: Folder not found at '{""}'")

get_files()
print(files_list)

import csv
with open("ACE_SW_Proton_Data_2004.txt", 'r', newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            print(row)

import csv
import os


def file_corrector(file_name):
  file_to_fix = file_name
  output_file = os.path.join("sample_corrected", file_to_fix)
  # Make sure the folder exists
  os.makedirs("sample_corrected", exist_ok=True)

  with open(file_to_fix, 'r', newline='', encoding='utf-8') as f, \
      open(output_file, 'w', newline='', encoding='utf-8') as laney:

      reader = csv.reader(f, skipinitialspace=True)  # adjust delimiter if needed
      writer = csv.writer(laney)

      for lineno, row in enumerate(reader, start=1):
          if lineno >= 36:     # keep only lines 36+
              writer.writerow(row)

for each in files_list:
  file_corrector(each)